### ISSUE TITLE
关于树大接口

### ISSUE THREAD

**Issue by dongshuyan** [LeiShi1313/Differential#2]
首先感谢大佬提供这么强的工具，想问一下：
1.我是否可以使用其他的一键转载接口呢（比如tomorrow505的脚本），因为我在那个上面自己进行了许多改进。我该如何操作呢？~

**Comment by LeiShi1313** [comment]
下个版本我可以加进去，树大的脚本其实只是提供了一个自动填充表单的功能，如果你有兴趣提交PR，可以从[这里](https://github.com/LeiShi1313/Differential/blob/main/differential/plugins/nexusphp.py#L103)入手，通过[`torrentInfo`](https://github.com/LeiShi1313/Differential/blob/main/differential/plugins/base.py#L565)构造出明日大佬脚本能识别的URL即可

**Comment by LeiShi1313** [comment]
@dongshuyan `0.2.0`已经支持了，加上`--auto-feed`就行
