### ISSUE TITLE
get_file_size() in the mediainfo digest request

### ISSUE THREAD

**Issue by GaryLz** [LeiShi1313/Differential#6]
差速器很好用，特别适合工作组发种。感谢感谢。

不过，在发种时，
发现 dft扫描视频文件，生成的mediainfo摘要 因为缺少本身的视频文件大小 file_size 项，

在一些渲染js后，会显得比较“奇怪”，甚至在某些站点因此会被report，希望开发者能有空做个小小的tweak
![photo_2022-03-08_23-45-53](https://user-images.githubusercontent.com/31096335/157273271-302afd07-0e24-45fd-a499-93dfcef03cb3.jpg)
![photo_2022-03-08_23-45-59](https://user-images.githubusercontent.com/31096335/157273286-13acb74f-b8d6-4561-92d7-78c08c720971.jpg)
![photo_2022-03-08_23-46-05](https://user-images.githubusercontent.com/31096335/157273290-1895bbeb-6205-4721-a1ee-c3f8ea47ffbb.jpg)

**Comment by LeiShi1313** [comment]
Fixed in 0.5.7
